name: flutter_delivery_app
description: Flutter Delivery App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6 # HTTP 통신 라이브러리
  flutter_secure_storage: ^7.0.1 # 보안이 적용된 저장소 라이브러리
  json_annotation: ^4.8.0 # JsonSerializable 라이브러리
  retrofit: '>=3.0.0 <4.0.0' # Retrofit 라이브러리
  logger: any # Retrofit 로그 라이브러리
  flutter_riverpod: ^2.1.3 # RiverPod 상태관리 라이브러리
  skeletons: ^0.0.3 # 로딩 위젯 표시 라이브러리
  go_router: ^6.0.6 # 네비게이션 라이브러리
  badges: ^3.0.2 # 알림 카운트 배지 라이브러리
  uuid: ^3.0.7 # UUID 생성 라이브러리
  debounce_throttle: ^2.0.0 # 함수(API) 실행 제한 라이브러리

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.3.3 # JsonSerializable 라이브러리
  json_serializable: ^6.6.0 # JsonSerializable 라이브러리
  retrofit_generator: '>=4.0.0 <5.0.0'

flutter:

  uses-material-design: true

  assets:
    - asset/img/misc/
    - asset/img/food/
    - asset/svg/icon/
    - asset/img/logo/
    - asset/rive/

  fonts:
    - family: NotoSans
      fonts:
        - asset: asset/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: asset/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: asset/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: asset/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: asset/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: asset/fonts/NotoSansKR-Thin.otf
          weight: 100